name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (для инфы, на runner'е)
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/crewlly

            echo "Pull latest code..."
            git pull origin main

            echo "Stop current containers..."
            docker compose --env-file .env.production -f docker-compose.prod.yml down

            echo "Build images WITHOUT cache..."
            docker compose --env-file .env.production -f docker-compose.prod.yml build --no-cache

            echo "Start containers..."
            docker compose --env-file .env.production -f docker-compose.prod.yml up -d --force-recreate

            echo "Cleanup old images (optional)..."
            docker image prune -f
